### ISSUE TITLE
bug: style property doesn't work in some cases

### ISSUE THREAD

**Issue by spion** [ionic-solidjs/ionic-solidjs#13]
It looks like the new style of prop passing may've broken passing css custom properties, e.g.

```typescript
            <IonFabButton
              size="small"
              style={{
                '--background': 'none',
                '--box-shadow': 'none',
                '--color': 'var(--ion-toolbar-color)',
              }}
```

no longer works

**Comment by spion** [comment]
Same applies for `class` - it seems like both must be passed as HTML attributes instead

**Comment by spion** [comment]
Hmm. For some reason, this still doesn't seem to work in certain cases, although `class` does work now. I'm unable to make a simple repro, but leaving it open for now as a reminder for the future.

**Comment by Hookyns** [comment]
This seems like a big issue. And it makes total sense to me now. Those are HTML attributes that should be inside HTML. class, style, contentEditable, title and so on,.. If you use the HTML Element JS properties, you can reassign current value or something/somebody can reassign your value.

This is a typical issue.
```javascript
const myDiv = document.createElement("div");
myDiv.onclick = () => doSomething();
myDiv.onclick = () => doSomethingElse(); // This will reassign the onclick event; old event handler is removed
```

When we use `prop:` property, it is direct assignment to JS property on the element, like the `onclick` above. So if the Ionic component itself assigns something to those properties, it will probably remove our assignments.
We should probably assign HTML attributes to props without `prop:` directive or we should use `attr:` to force the prop being handled as HTML attribute. 
But if you say it does not work properly, there is something strange happening and it must be something inside Ionic or Stencil.

EDIT:
But if this is true, we would have to make a list of all HTML attributes so we can handle them. But there are probably some Ionic properties that conflict with HTML attributes names. 
Maybe we can change TS declarations of components's props and rename all their HTML attributes to `attr:${TAttr}` so developers directly will use the `attr:` so we don't have to handle that. We can handle eg. just the class, style and some other common attributes, but it would be inconsistent.

EDIT2: The worst case scenario,.. if we would have to somehow handle that manually we should rather whitelist properties of components and pass them with `prop:`. Anything else should be passed with `attr:`. We can use my TS reflection to extract property names from Ionic component and create those whitelists as a build step. (So it's static at runtime).

**Comment by Hookyns** [comment]
@spion Do you have some examples where the class/style fails?

I implemented generator based on reflection so I'd like to test it.
All I tested is working.

![image](https://github.com/ionic-solidjs/ionic-solidjs/assets/2551259/291f7ba2-bc31-4b1b-8d17-fee1813beaa1)

![image](https://github.com/ionic-solidjs/ionic-solidjs/assets/2551259/f67c9bd5-7231-4aad-bc72-efe3443c1577)

How the generated components looks like now:
![image](https://github.com/ionic-solidjs/ionic-solidjs/assets/2551259/ec1dbafe-819f-4bc0-8703-b9a4fd8b1d37)

**Comment by spion** [comment]
I cannot reproduce the issue outside my larger project, especially after the regex update for `class` and `style`. I'm inclined to leave this be for now until there is a definite repro.

**Comment by Hookyns** [comment]
Just adding some info about what I found inside Solid.js. I may help us make a decision.

How the props are assigned to Node
https://github.com/ryansolid/dom-expressions/blob/c8dc99b1299cd03d2e59a0da04c414c44080a833/packages/dom-expressions/src/client.js#L313-L361

HTML attributes and events are whitelisted, based on this consts
https://github.com/ryansolid/dom-expressions/blob/c8dc99b1299cd03d2e59a0da04c414c44080a833/packages/dom-expressions/src/constants.js#L87

**Comment by spion** [comment]
It looks like `ref` doesn't work either. Not 100% sure if its related or not. edit: Based on the code links above, it is.

Hmm. My thoughts on this are that if we're doing anything more complicated with reflection, we should probably be careful about performance implication of lookups in (slightly longer) arrays. (e.g. testing whether pre-initialized sets outside of the component function yield better performance)

**Comment by spion** [comment]
To get my project unblocked, I'll update the regex to include `ref` in the excluded `props`, but happy to collaborate on the getType / reflection solution. The only bit I worry about is performance - not the reflection aspect as I understand you're targeting compile-time, but just how performant longer lists are to check.

**Comment by Hookyns** [comment]
I think we do prop:ref now so it's not ref technically. You have to exclude it like you excluded class and style.

**Comment by spion** [comment]
Thats what I meant. Words are difficult :grinning:

**Comment by Hookyns** [comment]
> Thats what I meant. Words are difficult 😀

Ahh,.. no. I didn't read the last message,.. I send it right after you posted it.. 😃

**Comment by Hookyns** [comment]
I can optimize it a little bit

```typescript
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-accordion'
import type { JSX as IonicJSX } from '@ionic/core'
import { type JSX as JSXBase, splitProps } from 'solid-js'
import type { FixIonProps } from '../../lib'

defineCustomElement()

export type IonAccordionProps = FixIonProps<IonicJSX.IonAccordion> &
	JSXBase.HTMLAttributes<HTMLIonAccordionElement>

export function IonAccordion(props: IonAccordionProps) {
	const [ _, rest ] = splitProps(
		props, 
		['disabled', 'mode', 'readonly', 'toggleIcon', 'toggleIconSlot', 'value']);
	const componentProps = () => ({
		'prop:disabled': props.disabled,
		'prop:mode': props.mode,
		'prop:readonly': props.readonly,
		'prop:toggleIcon': props.toggleIcon,
		'prop:toggleIconSlot': props.toggleIconSlot,
		'prop:value': props.value
	});

	return <ion-accordion {...componentProps()} {...rest} />;
}
```
that generates JS:
```javascript
export function IonAccordion(props) {
  const [_, rest] = splitProps(props, ["disabled", "mode", "readonly", "toggleIcon", "toggleIconSlot", "value"]);
  const componentProps = () => ({
    "prop:disabled": props.disabled,
    "prop:mode": props.mode,
    "prop:readonly": props.readonly,
    "prop:toggleIcon": props.toggleIcon,
    "prop:toggleIconSlot": props.toggleIconSlot,
    "prop:value": props.value
  });
  return (() => {
    var _el$ = _tmpl$();
    _$spread(_el$, _$mergeProps(componentProps, rest), false, false);
    _el$._$owner = _$getOwner();
    return _el$;
  })();
}
```

We cannot avoid that spread it generates but we can maybe avoid that splitProps with mergeProps if we implement that manually, somehow.

Version with the reflection based generator is here: https://github.com/Hookyns/ionic-solidjs/tree/features/reflection-based-solution-for-props-vs-attrs

**Comment by spion** [comment]
I understand now, splitProps is provided by Solid as it preserves prop reactivity properly. I think it should be OK even without the optimizations now that I've looked at the implementation (https://github.com/solidjs/solid/blob/a72d393a07b22f9b7496e5eb93712188ccce0d28/packages/solid/src/server/rendering.ts#L166)

None of the ionic component props look particularly long, and since this is not React it doesn't happen on every render :grinning:

**Comment by spion** [comment]
I think this is effectively resolved. Thank you for your contributions, this is starting to look pretty awesome at this point :grinning:
