### ISSUE TITLE
Remove the "simple" router

### ISSUE THREAD

**Issue by spion** [ionic-solidjs/ionic-solidjs#18]
After migrating to `IonRouter` in my apps, everything seems to behave normally (There is doubling of animation after vue HMR, but that's a minor issue).

Based on that, I'm not sure we need the "simple" router at all anymore.

**Comment by Hookyns** [comment]
Yeah,.. maybe we can keep it for the more complex implementation with solid router? Like Ionic use react router. IDK if it's worthy.

**Comment by spion** [comment]
Removed for now.
