### ISSUE TITLE
Add release-please

### ISSUE THREAD

**Issue by spion** [ionic-solidjs/ionic-solidjs#3]
I've used it in projects before and its probably the nicest semantic release system with high degree of control.

Will try to install it here too

Some docs: https://github.com/googleapis/release-please/blob/cb106cd0b5ae5c3e2a3b015487dc615eba72b842/docs/manifest-releaser.md

**Comment by Hookyns** [comment]
What about lerna (https://lerna.js.org) and lerna changelog (https://github.com/lerna/lerna-changelog)?

**Comment by spion** [comment]
Can it create PRs like this where it aggregates changes published thus far, then release when release-pr is merged? https://github.com/spion/wsrun-ng/pull/7

**Comment by spion** [comment]
I can see using `lerna publish` instead of `bun wsrun -s -c publish` but I don't understand why it insists on incrementing the version too https://lerna.js.org/docs/features/version-and-publish#publishing-to-npm

- https://github.com/lerna/lerna/issues/1868

edit: looks like `lerna publish from-git` might do the trick as per https://github.com/lerna/lerna/issues/1767
