### ISSUE TITLE
Bundle size issue

### ISSUE THREAD

**Issue by erfanmola** [ionic-solidjs/ionic-solidjs#34]
Hi, first of all thanks for this amazing piece of code and long live to SolidJS. I have just started using this library and a huge issue I'm facing is the bundle size when building the project.

I only have this line of code in my empty boilerplate solidjs code:
`import { IonButton } from '@ionic-solidjs/core';`

when I do a build, it outputs a JS file that is `1,016KB` which is huge for an empty project, is there a reason behind it? or am I missing something?

**Comment by spion** [comment]
edited: Never mind, I misread the original message. This is about bundle size even without using the icons package.

**Comment by spion** [comment]
We may need to completely rework the icon generation to support DCE. Specifically:

- possibly remove tsup from the equation
- generate `.d.ts`, `.mjs` and `.js` files separately for each icon. `.mjs` and `.js` would contain the icon content itself directly
- eliminate dependency of ionicons

I think that DCE might still not work  on the main icon indexdue to the `addIcon` side effect, but its worth giving it a try.

**Comment by spion** [comment]
Looking at it some more, it loooks like the reasons might be similar for both the icons package and the components package. 

Namely, both use side-effects to register the icons / define custom components (example https://github.com/ionic-solidjs/ionic-solidjs/blob/main/packages/core/src/components/generated/ion-accordion.tsx#L8), which combined with bundling is likely to trigger rollup tree-shaking to include all of them.

A fix we could try would probably be to get rid of tsup and generate the individual module files and type definitions directly (.cjs .mjs and .d.ts), and to ensure that the index file doesn't bundle them.

**Comment by erfanmola** [comment]
Thanks for the response and detailed explanation, is there any help I could provide for the process?

**Comment by spion** [comment]
I think I found a simple way to do this in #35

**Comment by spion** [comment]
The base bundle size should be much lower with the latest core (v1.2.1) and ionicons (v1.1.1). The small todo example is now 300KB (66KB gzipped) instead of 1MB. Let me know whether this works on your end.
